### ISSUE TITLE
Add a "Remove animations" CTA button for first page animations

### ISSUE THREAD

**Issue by mwritter** [google/web-stories-wp#11474]
## Feature Description

Animations on the first page are no longer supported by AMP, and the user does not have simple way to remove the disable animations - (see #11448 ).  We currently disable all animations on the first page and show a checklist item, so there’s actually no way to get rid of this warning (except for removing all elements on the first page and then adding them again without animations) - (see #11416 ). Add a new 'Remove Animations' button in the Checklist item 'First Page Animations' giving the user a simple way to remove all animations from the story's first page and remove the 'First Page Animations' warning/checklist item.

## Additional Context

![screenshot](https://user-images.githubusercontent.com/14057928/167865377-bb95b375-e494-4a95-b6fa-b6e206f05979.png)

**Comment by felipebochehin87** [comment]
Tested against https://stories-qa-wordpress-amp.pantheonsite.io/wp-admin, using PR #11476.

1. Started a new story
2. Added elements to the story
3. Duplicated page many times
4. Added animation to the second page
5. Deleted first page
6. Clicked on the element from the first page (the one that was the second page)
7. Clicked on the checklist - Remove Animations is displayed

Also tested clicking on "Remove Animations" being on a page that is not the 1st - confirmed that the animation is removed only from the first page - other pages are not affected.
