### ISSUE TITLE
Got ERR_MODULE_NOT_FOUND error while build plugin

### ISSUE THREAD

**Issue by lucemia** [google/web-stories-wp#4157]
## Bug Description

Thanks for the great project!

I try to build the plugin by myself, when I run `npm run workflow:build-plugin --zip`
I got the following error:

```
> web-stories-wp@ workflow:build-plugin /Users/foobar/repo/web-stories-wp
> ./bin/commander.js build-plugin

internal/process/esm_loader.js:74
    internalBinding('errors').triggerUncaughtException(
                              ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/Users/foobar/repo/web-stories-wp/bin/build/migrate.js' imported from /Users/foobar/repo/web-stories-wp/bin/utils/updateTemplates.js
    at finalizeResolution (internal/modules/esm/resolve.js:275:11)
    at moduleResolve (internal/modules/esm/resolve.js:719:10)
    at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:809:11)
    at Loader.resolve (internal/modules/esm/loader.js:85:40)
    at Loader.getModuleJob (internal/modules/esm/loader.js:229:28)
    at ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:51:40)
    at link (internal/modules/esm/module_job.js:50:36) {
  code: 'ERR_MODULE_NOT_FOUND'
```

## Expected Behaviour

build plugin zip successfully

## Steps to Reproduce

1. clone the project
2. npm run build
3. npm run workflow:build-plugin --zip

## Additional Context

- Plugin Version: 28aa224e5fac88a73a7ef7cf39514d3c66b0c7a8
- Operating System: Mac
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
Running `npx rollup --config bin/rollup.config.migrate.js` is currently a pre-requisite for this command to work.

**Comment by lucemia** [comment]
> Running `npx rollup --config bin/rollup.config.migrate.js` is currently a pre-requisite for this command to work.

thanks, it works!
