### ISSUE TITLE
Tech Debt: Remove copies of `useFocusOut`

### ISSUE THREAD

**Issue by samwhale** [google/web-stories-wp#7166]
## Feature Description

There's a copy of `useFocusOut` in the design system, dashboard, and editor. These should be combined into one hook to prevent regressions and keep a single source of truth.

## Alternatives Considered

n/a

## Additional Context

- https://github.com/google/web-stories-wp/blob/main/assets/src/design-system/utils/useFocusOut.js
- https://github.com/google/web-stories-wp/blob/main/assets/src/dashboard/utils/useFocusOut.js
- https://github.com/google/web-stories-wp/blob/main/assets/src/edit-story/utils/useFocusOut.js

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by csossi** [comment]
Verified in QA
