### ISSUE TITLE
Taxonomy: Give Hierarchical Search Input a Placeholder

### ISSUE THREAD

**Issue by BrittanyIRL** [google/web-stories-wp#9300]
This is a hold over until we can unify our search inputs in the editor. Let's start by giving the search input on hierarchical components a placeholder - can use the name that comes from the `taxonomy.labels` to make sure it stays accurate for whatever custom taxonomies a user might have. 

Update 10.6.2021 3pm MST - additional request made to add the 'search' icon to make this search input look more like others in the editor instead of like Gutenberg.

(created from #9285 )

**Comment by BrittanyIRL** [comment]
@littlemilkstudio - Per Amy's request here an hour ago can you add the magnifying glass to your existing PR otherwise let's follow it up separately. Just wanted to mention it here so this ticket doesn't get closed preemptively. 

https://github.com/google/web-stories-wp/issues/9285#issuecomment-937060870

**Comment by csossi** [comment]
Verified in QA
