### ISSUE TITLE
Web Stories block incompatibility with AMP for WP plugin

### ISSUE THREAD

**Issue by DanielCryptoK** [google/web-stories-wp#9314]
Hi, I posted the below in the wordpress forum but they are saying its a bug and there is no idea when it will be fixed.  I have now been trying for more than a year to get these web stories live, but had to wait for updates. Please can someone help me finally get them live as it is so frustrating to spend a whole year on something and it still not work.

I can not get the web stories to display, please see here https://www.webpagescreenshot.info/#v2=fYajXe3WC

Example web story below

https://nonfungibleownership.com/web-stories/sandbox-review/

Page not displaying on

https://nonfungibleownership.com/nft-art-tokens/

The page I need help with: https://nonfungibleownership.com/nft-art-tokens/

This was the reply:

@bitcoincasino666 Hello, you may be experiencing a known issue with amp-story-player as reported in the broader AMP service, ampproject/amphtml#35959.

Unfortunately, I don’t have a timeline on when this will be resolved, but we will update you here when the fix has been released.

**Comment by swissspidy** [comment]
Hi @DanielCryptoK 

I understand that it can be frustrating to deal with such issues. However, please note that support questions should be asked in the support forums and not simply escalated to GitHub because the issue is still happening. We concentrate our support offering on the forums, so let’s please use those.

Regarding your page https://nonfungibleownership.com/nft-art-tokens/, there are tons of AMP validation errors.

Try disabling the AMP for WP plugin and let us know in your thread on the forums whether that helps. If not, try disabling all other plugins to check the difference.

This is most likely an issue with that plugin or a combination of plugins.

Again, let us know in the forums once you‘ve disabled the pkugin(s).

**Comment by DanielCryptoK** [comment]
Hi,

My website is AMP first so will be very bad turning it off. The AMP validation errors are coming from the web stories plugin. Could it be that because me website is AMP first which is causing the error?

The attribute 'role' in tag 'div' is missing or incorrect, but required by attribute 'on'.
15 instances
Line 151:3905
<div class="web-stories-list__story" on="tap:AMP.setState({lightbox16041: ! lightbox16041})"> <div class="web-stories-list__story-poster"> <amp-img sr
Line 151:4477
<div class="web-stories-list__story" on="tap:AMP.setState({lightbox15861: ! lightbox15861})"> <div class="web-stories-list__story-poster"> <amp-img sr
Line 151:5044
<div class="web-stories-list__story" on="tap:AMP.setState({lightbox15841: ! lightbox15841})"> <div class="web-stories-list__story-poster"> <amp-img sr
Line 151:5631
<div class="web-stories-list__story" on="tap:AMP.setState({lightbox15391: ! lightbox15391})"> <div class="web-stories-list__story-poster"> <amp-img sr
Line 151:6171
<div class="web-stories-list__story" on="tap:AMP.setState({lightbox14711: ! lightbox14711})"> <div class="web-stories-list__story-poster"> <amp-img sr
Line 152:350
<div class="story-lightbox__close-button" on="tap:lightbox-16041.close"> <span class="story-lightbox__close-button--stick"></span> <span class="story-
Line 152:1222
<div class="story-lightbox__close-button" on="tap:lightbox-15861.close"> <span class="story-lightbox__close-button--stick"></span> <span class="story-
Line 152:2079
<div class="story-lightbox__close-button" on="tap:lightbox-15841.close"> <span class="story-lightbox__close-button--stick"></span> <span class="story-
Line 152:2944
<div class="story-lightbox__close-button" on="tap:lightbox-15391.close"> <span class="story-lightbox__close-button--stick"></span> <span class="story-
Line 152:3786
<div class="story-lightbox__close-button" on="tap:lightbox-14711.close"> <span class="story-lightbox__close-button--stick"></span> <span class="story-
Line 152:4715
<div class="story-lightbox__close-button" on="tap:lightbox-16042.close"> <span class="story-lightbox__close-button--stick"></span> <span class="story-
Line 152:5587
<div class="story-lightbox__close-button" on="tap:lightbox-15862.close"> <span class="story-lightbox__close-button--stick"></span> <span class="story-
Line 152:6444
<div class="story-lightbox__close-button" on="tap:lightbox-15842.close"> <span class="story-lightbox__close-button--stick"></span> <span class="story-
Line 152:7309
<div class="story-lightbox__close-button" on="tap:lightbox-15392.close"> <span class="story-lightbox__close-button--stick"></span> <span class="story-
Line 152:8151
<div class="story-lightbox__close-button" on="tap:lightbox-1

The attribute 'tabindex' in tag 'div' is missing or incorrect, but required by attribute 'on'.
15 instances
Line 151:3905
<div class="web-stories-list__story" on="tap:AMP.setState({lightbox16041: ! lightbox16041})"> <div class="web-stories-list__story-poster"> <amp-img sr
Line 151:4477
<div class="web-stories-list__story" on="tap:AMP.setState({lightbox15861: ! lightbox15861})"> <div class="web-stories-list__story-poster"> <amp-img sr
Line 151:5044
<div class="web-stories-list__story" on="tap:AMP.setState({lightbox15841: ! lightbox15841})"> <div class="web-stories-list__story-poster"> <amp-img sr
Line 151:5631
<div class="web-stories-list__story" on="tap:AMP.setState({lightbox15391: ! lightbox15391})"> <div class="web-stories-list__story-poster"> <amp-img sr
Line 151:6171
<div class="web-stories-list__story" on="tap:AMP.setState({lightbox14711: ! lightbox14711})"> <div class="web-stories-list__story-poster"> <amp-img sr
Line 152:350
<div class="story-lightbox__close-button" on="tap:lightbox-16041.close"> <span class="story-lightbox__close-button--stick"></span> <span class="story-
Line 152:1222
<div class="story-lightbox__close-button" on="tap:lightbox-15861.close"> <span class="story-lightbox__close-button--stick"></span> <span class="story-
Line 152:2079
<div class="story-lightbox__close-button" on="tap:lightbox-15841.close"> <span class="story-lightbox__close-button--stick"></span> <span class="story-
Line 152:2944
<div class="story-lightbox__close-button" on="tap:lightbox-15391.close"> <span class="story-lightbox__close-button--stick"></span> <span class="story-
Line 152:3786
<div class="story-lightbox__close-button" on="tap:lightbox-14711.close"> <span class="story-lightbox__close-button--stick"></span> <span class="story-
Line 152:4715
<div class="story-lightbox__close-button" on="tap:lightbox-16042.close"> <span class="story-lightbox__close-button--stick"></span> <span class="story-
Line 152:5587
<div class="story-lightbox__close-button" on="tap:lightbox-15862.close"> <span class="story-lightbox__close-button--stick"></span> <span class="story-
Line 152:6444
<div class="story-lightbox__close-button" on="tap:lightbox-15842.close"> <span class="story-lightbox__close-button--stick"></span> <span class="story-
Line 152:7309
<div class="story-lightbox__close-button" on="tap:lightbox-15392.close"> <span class="story-lightbox__close-button--stick"></span> <span class="story-
Line 152:8151
<div class="story-lightbox__close-button" on="tap:lightbox-1

**Comment by swissspidy** [comment]
Hi Daniel

Yes, I understand that and I did see the AMP validation error.

What I am suggesting is to **temporarily** disable the plugin to see if it makes a difference. Just for a few minutes.

The Web Stories plugin 100% supports AMP and we support and recommend using [the official AMP plugin](https://wordpress.org/plugins/amp/) for doing so. Especially for AMP first sites. With it, you should have a fully functioning stories embeds and no validation errors whatsoever. It's really straightforward to use.

We don't officially support the AMP for WP plugin which you are using and is a different plugin, since it is severely limited in its capabilities to ensure AMP validation.

That said, we'll do some more testing with AMP for WP to see how we could improve the situation a bit.

**Comment by csossi** [comment]
Verified in QA:
![image](https://user-images.githubusercontent.com/16945664/136667743-ac245a71-17a6-4585-80ff-4407627f9ef9.png)

(Note: poster images as being pulled in for the circle carousel, but not for the box carousel nor the grid)

**Comment by DanielCryptoK** [comment]
Hi, I tried what you suggested and changed to amp official but was disaster. Please can you tell me how to make a back up of just the webstories as I need to reset my website to an earlier day but do not want to lose all the web stories created after that day.

Is there a certain file I can copy and then replace it once the reset is done?

If I backed up plugins and images would that solve it?

Many thanks

**Comment by swissspidy** [comment]
Hi @DanielCryptoK 

I always responded to your question in the forums, see https://wordpress.org/support/topic/file-name-for-webstories/

We‘ll have better support for the AMP for WP plugin in our next release too, so you can keep using it.
