### ISSUE TITLE
Post Types: Create a new Post type base class

### ISSUE THREAD

**Issue by spacedmonkey** [google/web-stories-wp#9316]
## Feature Description
In #9047, we create a Taxonomy base class, designed to make creating taxonomies more generate and DRY. A base post type class could be created to perform a similar action. Using a similar format as [Taxonomy_Base](https://github.com/google/web-stories-wp/blob/main/includes/Taxonomy/Taxonomy_Base.php), repeated logic could moved moved to this base class. Examples. 

https://github.com/google/web-stories-wp/blob/26826bf3391645624c42d2498d9c239083ff590c/includes/Story_Post_Type.php#L122-L132

https://github.com/google/web-stories-wp/blob/26826bf3391645624c42d2498d9c239083ff590c/includes/Story_Post_Type.php#L134-L144

https://github.com/google/web-stories-wp/blob/26826bf3391645624c42d2498d9c239083ff590c/includes/Story_Post_Type.php#L146-L156

https://github.com/google/web-stories-wp/blob/26826bf3391645624c42d2498d9c239083ff590c/includes/Story_Post_Type.php#L219-L228

We could also take this opportunity, to get rid of the trait [Post_Type](https://github.com/google/web-stories-wp/blob/main/includes/Traits/Post_Type.php). We can change the signature of the method from this 
```
$this->get_post_type_cap( $this->story_post_type::POST_TYPE_SLUG, 'edit_posts' )
```
to
```
$this->story_post_type->cap( 'edit_posts' ) 
```

**Comment by swissspidy** [comment]
> We could also take this opportunity, to get rid of the trait `Post_Type`

Absolutely. I'd say this is a **must** for this ticket.
