### ISSUE TITLE
Uncaught promise rejections when using `preloadImage`

### ISSUE THREAD

**Issue by miina** [google/web-stories-wp#9326]
## Bug Description
There's a console error displayed when saving a new page template with images.
Let's figure out if there's actually anything broken and add handle the error properly.

## Steps to Reproduce
1. Create a new page with some images
2. Go to the Page Templates tab in the library and add click to save a new template
3. See the console error

## Screenshots
<img width="470" alt="Screenshot 2021-10-07 at 12 31 20" src="https://user-images.githubusercontent.com/3294597/136520649-9048ef2c-ec37-4f7b-ad5f-734554653692.png">
<img width="1439" alt="Screenshot 2021-10-07 at 12 30 50" src="https://user-images.githubusercontent.com/3294597/136520659-e2142a31-2819-415a-9702-9cc84c1e686e.png">

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

**Comment by swissspidy** [comment]
I wasn't able to reproduce this, but I'll try again.

We should have some `.catch()` / `try { } catch {}` everywhere `preloadImage` is used as a last resort for sure.

**Comment by miina** [comment]
> I wasn't able to reproduce this, but I'll try again.

Hm, I removed all the existing page templates to try it again completely with a completely clean story, and now I'm not able to reproduce it either. The previously existing templates from yesterday's testing didn't have any broken media (that could be a reason to cause this, I guess), so not sure what caused it 🤔

**Comment by swissspidy** [comment]
Let's add some safeguards in any case 👍
