### ISSUE TITLE
URL for the attribute "CTA-image" in the tag "amp-story-page-outlink" is missing

### ISSUE THREAD

**Issue by ronicacio** [google/web-stories-wp#9348]
Hello, I'm going through a web story validation error: the URL for the attribute "CTA-image" in the tag "amp-story-page-outlink" is missing.

Any idea how you fix that?

https://search.google.com/test/amp/result?id=gZQ94oKAVflP8cq1-IM8Lw

**Comment by swissspidy** [comment]
Thanks for your report!

We've already fixed this issue in #9307 and will be releasing an updated version of the plugin in the next 1-2 days to address this. Just keep an eye open for that update.

**Comment by ronicacio** [comment]
Thank's
