### ISSUE TITLE
Video Optimization: Reuse existing resource if exists

### ISSUE THREAD

**Issue by swissspidy** [google/web-stories-wp#9384]
### Scenario

* You have an original unoptimized video and place it on the canvas
* You optimize it
* You create a new story and place the original unoptimized video on the canvas
* You optimize it
* This will result in another optimized version being created instead of just using the original

### How to possibly fix this

1. When optimizing an existing video, fetch `/web-stories/v1/media/<resource_id>` and check for `meta.web_stories_optimized_id`.
2. If `meta.web_stories_optimized_id` is set, grab `/web-stories/v1/media/<optimized_id>` and replace the existing resource with the optimized one

**Comment by csossi** [comment]
Verified in QA
