### ISSUE TITLE
Pre-Publish Checklist: Improve image resolution check description

### ISSUE THREAD

**Issue by swissspidy** [google/web-stories-wp#9401]
## Feature Description

The image resolution check in the checklist flags all images with low pixel density (< 2x).

i.e. if your image element is 400x400px, the image needs to be at least 800x800px in size so that it's displayed in good quality to the user, especially on HiRes screens.

However, the description does not say this to the user **at all**. It talks about 828x1792px and full-screen images, even when you just have some small image somewhere on the canvas.

This is very confusing to users.

![Screenshot 2021-10-11 at 10 59 29](https://user-images.githubusercontent.com/841956/137126024-625149c1-2b43-4540-9979-28bed5d7fc03.png)

Suggesting something along these lines

**Title:** `Increase image resolution`
**Description:**
```
* Use Retina images for best appearance on high resolution screens.
* For full-screen images, use a resolution of at least 828x1792px
```

Giving an example of what's needed or mentioning the "2x resolution" would be good though.

And the full-screen part should perhaps only be mentioned if it's actually a full-screen (background) image.

**Also:**

There's a TODO in the code that mentions the check does not accommodate for scaling. Scaling should be considered too.

## Additional Context

* This came from user feedback through support.

**Comment by BrittanyIRL** [comment]
@choumx or @gajasinski can you verify that you're ok with the above language Pascal is suggesting?

**Comment by gajasinski** [comment]
LGTM

**Comment by dreamofabear** [comment]
Nit: I'd replace the platform-specific "Retina" term with more neutral "pixel density". E.g.

> Use larger resolution (2x or 3x) images for best appearance on screens with high pixel density.

https://web.dev/codelab-density-descriptors/

**Comment by BrittanyIRL** [comment]
use https://github.com/google/web-stories-wp/pull/9440 to test this copy change

**Comment by csossi** [comment]
Verified in QA
