### ISSUE TITLE
Pre-Publish Checklist Double Scrollbars

### ISSUE THREAD

**Issue by swissspidy** [google/web-stories-wp#9404]
## Bug Description

In the pre-publish checklist, when there are a few warnings, there can be some double scrollbars. That looks a bit odd and would be nice to fix.

## Expected Behaviour

No double scrollbars :-)

## Steps to Reproduce

Create a story that causes some warnings to pop up in the checklist.

## Screenshots

![Screenshot 2021-10-11 at 10 59 43](https://user-images.githubusercontent.com/841956/137137977-a651ae91-a137-4a9e-ab59-2aaceeb9ed71.png)

## Additional Context

- Plugin Version: 1.13.0
- WordPress Version: 5.8
- Operating System: macOS
- Browser: Chrome

**Comment by BrittanyIRL** [comment]
Agree - thanks for making a ticket

**Comment by csossi** [comment]
Verified in QA
