### ISSUE TITLE
Single story embed not rendering

### ISSUE THREAD

**Issue by LuckynaSan** [google/web-stories-wp#9410]
## Bug Description

Stories that have been embedded using the embed block or inserting a shortcode are not rendering on the page. The story embed is visible when previewing the page, but after you update/publish the embedded story it no longer displays.

## Expected Behaviour

For the stories embed block or shortcode to render and display stories. 

## Steps to Reproduce

1) embed a story using the embed single story URL block <img width="447" alt="Screen Shot 2021-10-14 at 12 04 00 PM" src="https://user-images.githubusercontent.com/66372350/137360587-a99b8211-14d0-4c75-b48f-7c311083a944.png">
2) preview post
3) update/publish a post
4) visit the page
5) note story player does not appear
6) Activate classic editor, Insert shortcode, and repeat steps

## Screenshots
**Actual results:**
   (initial page load)
<img width="1051" alt="Screen Shot 2021-10-14 at 11 58 15 AM" src="https://user-images.githubusercontent.com/66372350/137361350-b84be525-563e-4769-b429-2f01da70121b.png">
   (after page loads)
<img width="994" alt="Screen Shot 2021-10-14 at 11 53 22 AM" src="https://user-images.githubusercontent.com/66372350/137361270-37b6214c-dd95-401b-9f53-92c2fbba78df.png">

**Expected results:** 
<img width="1103" alt="Screen Shot 2021-10-14 at 11 53 15 AM" src="https://user-images.githubusercontent.com/66372350/137361218-5087c221-60e6-4350-804c-afa2a3c80978.png">

**Console errors:**
<img width="581" alt="Screen Shot 2021-10-14 at 11 54 25 AM" src="https://user-images.githubusercontent.com/66372350/137360522-a2cc270b-d140-4db1-b583-2bac0f305d47.png">

## Additional Context

Original user report: https://wordpress.org/support/topic/embeds-stopped-working/
Test site: https://testsite.cmsdevrel.com

- Plugin Version: 1.13.0
- WordPress Version:
- Operating System: macOS
- Browser: Chrome

**Comment by ArtFl-2** [comment]
Just wanted to add that if you are using a classic editor and enter a shortcode the story is not visible even in the preview mode.

**Comment by csossi** [comment]
Verified in QA
