### ISSUE TITLE
Close button no longer displays on story player

### ISSUE THREAD

**Issue by LuckynaSan** [google/web-stories-wp#9411]
## Bug Description
The close button no longer displays on stories. For example, https://testsite.cmsdevrel.com/web-stories/test-the-x-icon/

Actual results:
<img width="1388" alt="Screen Shot 2021-10-14 at 1 14 49 PM" src="https://user-images.githubusercontent.com/66372350/137365973-a31ee40d-77de-4bd8-be0f-f619107f51d4.png">

Expected results:
<img width="698" alt="Screen Shot 2021-10-14 at 1 16 45 PM" src="https://user-images.githubusercontent.com/66372350/137365987-79120aca-e2c9-498d-865b-1b54308aaad1.png">

## Steps to Reproduce

1) publish/view story
2) note missing "x" close button

## Additional Context

- Plugin Version: 1.13.0
- WordPress Version:
- Operating System: macOS
- Browser: Chrome

**Comment by swissspidy** [comment]
@LuckynaSan https://testsite.cmsdevrel.com/web-stories/test-the-x-icon/ is the permalink of the story. It's not a lightbox. So there can't be no X.

The second screenshot is a story in a lightbox, so it has the X.
