### ISSUE TITLE
Checklist: Image Resolution Check Should Consider Scale

### ISSUE THREAD

**Issue by BrittanyIRL** [google/web-stories-wp#9439]
Currently the PPC check for image resolution isn't considering scale, it should. 

Follow up from #9401.

**Comment by swissspidy** [comment]
Is scale relevant for the video resolution check as well?

**Comment by samwhale** [comment]
I think I'm a little confused about what we're looking for here. What are we defining as the threshold to where a user has scaled into the image too much?

Ex: This image (from 3p media) is zoomed into 400%, but the image still displays clearly, right? @swissspidy 
![image.png](https://images.zenhubusercontent.com/5b1032a1348b7966b43421a4/b85756f4-51c1-44e9-93ad-6539c8082426)

**Comment by BrittanyIRL** [comment]
> I think I'm a little confused about what we're looking for here. What are we defining as the threshold to where a user has scaled into the image too much? 

Great question, I think this needs a little infra clarification to get on the same page. @spacedmonkey or @swissspidy when you get a sec can you chime in?

**Comment by swissspidy** [comment]
Why infra? 🤔 

I think input from @choumx might be more helpful here

**Comment by maxyinger** [comment]
I think I got an idea for what we want for images i.e:
```
image size > 2 * element size * element scale
````

However, it seems videos are different. Right now videos are just checked by:
```
video size > SOME_CONSTANT_VIDEO_SIZE
```

I'm not sure why video resolution is checked like this, but I'm assuming its some checklist context I'm missing

**Comment by BrittanyIRL** [comment]
> Why infra? 🤔

Oh just because of all the work you both have done surrounding media.  Looks like Max is onto something though.
