### ISSUE TITLE
UI Simplifications: Selection Panel

### ISSUE THREAD

**Issue by miina** [google/web-stories-wp#9460]
## Feature Description
See [Figma for details](https://www.figma.com/file/dc9xrVlRhQq4KTE9WQzU1R/_Editor-Sprint-Feature-Level-Designs_?node-id=10250%3A435609).

- [ ] Change the name of Size & Position to "Selection"
- [ ] Remove the Layer panel and move the opacity field to the new "Selection" panel
- [ ] Remove the Corner radius panel and move the input to the "Selection" panel. Redesign the input (see locked vs [unlocked](https://www.figma.com/file/dc9xrVlRhQq4KTE9WQzU1R/_Editor-Sprint-Feature-Level-Designs_?node-id=10250%3A436882) in Figma)
- [ ] Ensure the changes are reflected accurately in all element panels.

**Comment by csossi** [comment]
When clicked, the "Toggle consistent corner radius" pops up and stays on screen until the user clicks somewhere. Might it be better if it behaved like a candybar and disappear after a few seconds?:
![image](https://user-images.githubusercontent.com/16945664/139338094-7b01e69c-ed7b-4be9-a3ff-800c67dce1f0.png)

**Comment by miina** [comment]
> When clicked, the "Toggle consistent corner radius" pops up and stays on screen until the user clicks somewhere. Might it be better if it behaved like a candybar and disappear after a few seconds?:

This is a general behaviour with tooltips -- if focus is on the button, the Tooltip stays visible. For changing this, the behaviour of tooltips would generally need changing.

@BrittanyIRL Is there a way to force hiding a tooltip from the component? There are a few cases where a tooltip staying open has been reported as a bug but it's really due to the button having focus after clicking. E.g. the border panel locking-unlocking and when opening and closing the grid view. Asking you since I believe you have recently worked on a lingering-tooltip related issue (might have been a completely different issue though).
In this specific reported case, when clicking on the "unlock" button, the position of the button changes but focus stays on the button, so the tooltip stays visible in the same place even though it now covers some relevant parts. Thoughts?

**Comment by BrittanyIRL** [comment]
> > When clicked, the "Toggle consistent corner radius" pops up and stays on screen until the user clicks somewhere. Might it be better if it behaved like a candybar and disappear after a few seconds?:
> 
> This is a general behaviour with tooltips -- if focus is on the button, the Tooltip stays visible. For changing this, the behaviour of tooltips would generally need changing.
> 
> @BrittanyIRL Is there a way to force hiding a tooltip from the component? There are a few cases where a tooltip staying open has been reported as a bug but it's really due to the button having focus after clicking. E.g. the border panel locking-unlocking and when opening and closing the grid view. Asking you since I believe you have recently worked on a lingering-tooltip related issue (might have been a completely different issue though). In this specific reported case, when clicking on the "unlock" button, the position of the button changes but focus stays on the button, so the tooltip stays visible in the same place even though it now covers some relevant parts. Thoughts?

🤔  

so the 'lingering' issue was totally separate and due to the 💅  fancy style tricks on the color swatches. Having the tooltips remain open as long as the element it is attached to is in focus is in line with the accessibility rules that I know (https://dequeuniversity.com/library/aria/tooltip for a sanity check). So I'm thinking the thing to address here is the same as what @BrookeGraham  fixed with the dropdown recently (see taxonomy) where if the space changes while it's open it'll update position. 

Is that kinda what you're thinkin about? If so, pea pod can take that one.

**Comment by miina** [comment]
> So I'm thinking the thing to address here is the same as what BrookeGraham fixed with the dropdown recently (see taxonomy) where if the space changes while it's open it'll update position.
> Is that kinda what you're thinkin about? If so, pea pod can take that one.

Thanks for chiming in. Yes, updating the tooltip position would be a great solution for this case as well!
