### ISSUE TITLE
Archive Page Customization: Enable by default

### ISSUE THREAD

**Issue by swissspidy** [google/web-stories-wp#9481]

**Comment by csossi** [comment]
When I first selected Custom, I had two options - QA Test Page and Sample Page. Selected QA Test Page. Returned to settings to select Sample Page now, but am seeing this instead - QA Test Page duped:
![image](https://user-images.githubusercontent.com/16945664/138908171-6fa0fb91-86fe-41bc-a1bf-319f8b49f063.png)

**Comment by csossi** [comment]
Verified in QA
