### ISSUE TITLE
Baking Bread Guide Template Details Page: Page 11 Broken Poster Image

### ISSUE THREAD

**Issue by LuckynaSan** [google/web-stories-wp#9500]
## Bug Description

The Baking Bread Guide template's details page is displaying a broken poster image for page 11.

## Expected Behaviour

For the intended thumbnail poster image to display. 

## Steps to Reproduce

1. View Baking Bread Guide template's details page
2. See thumbnail Poster template of page 11 broken image

## Screenshots

<img width="1227" alt="Screen Shot 2021-10-22 at 9 59 22 AM" src="https://user-images.githubusercontent.com/66372350/138467517-63d2039f-999a-4274-8b6b-ed0a66653939.png">

## Additional Context

- Plugin Version: 1.13.0
- WordPress Version: 5.8.1
- Operating System: macOS
- Browser: Chrome

**Comment by BrittanyIRL** [comment]
ah i just fixed this 2 days ago!  #9485

**Comment by BrittanyIRL** [comment]
Claudio - this can be tested on staging, no PR associated with it.

**Comment by csossi** [comment]
Verified in QA
