### ISSUE TITLE
Video Captions gets flipped vertically along with the video

### ISSUE THREAD

**Issue by LuckynaSan** [google/web-stories-wp#9515]
## Bug Description
When you flip a video vertically, it also flips the captions. 

## Expected Behaviour

For the captions to remain the same. 

## Steps to Reproduce

1. Add video to story
2. Flip vertically
3. Add captions
4. Play video
5. Note captions are flipped vertically along with the video

## Screenshots

https://user-images.githubusercontent.com/66372350/138715049-ed07c742-f573-4d19-9344-ee0ad12e1a83.mov

## Additional Context

User report: https://wordpress.org/support/topic/video-captions-not-working-as-intended/

- Plugin Version: 1.13.0
- WordPress Version: 5.8.1
- Operating System: macOS
- Browser: Chrome

**Comment by swissspidy** [comment]
This will be fixed by #5315, which will be shipping with the next release.

Closing as a duplicate of #9216 which is the ticket for enabling the new feature by default.

**Comment by LuckynaSan** [comment]
Thanks!

**Comment by swissspidy** [comment]
@LuckynaSan To clarify, in our next release this will be done for the frontend only. Fixing the appearance in the editor will be done afterwards in #9344
