### ISSUE TITLE
Decoupling: Find alternative way to share test utilities

### ISSUE THREAD

**Issue by mohdsayed** [google/web-stories-wp#9516]
## Feature Description

`story-editor` package is currently exporting [testUtils](https://github.com/google/web-stories-wp/blob/main/packages/story-editor/src/index.js#L31) because [renderWithTheme](https://github.com/google/web-stories-wp/blob/main/packages/story-editor/src/testUtils/index.js#L17) utility function is being used in the `wp-story-editor` tests. However, this results in increasing the overall size of the chunk file `vendors-chunk-getStoryPropsToSave-wp-story-editor.js` by 186Kb ( 657kb - 471kb ).

We had the same issue when working with #9419 where the size of `venders-wp-dashboard.js` file was increased by 186kb ( 485kb - 299kb ). So we had to copy some of the code from `dashboard` to `wp-dashboard` to avoid exporting `testUtils`

## Alternatives Considered

1. Perhaps create a separate package for test utils to be shared between packages.
2. Copy required utility methods ( but would lead to code duplication )
3. Maybe find some way to exclude such test files getting bundled via webpack configuration.

## Additional Context

I think this increase went unnoticed because we had a relatively huge decrease when working on decoupling `story-editor` and `wp-story-editor`.

**Comment by swissspidy** [comment]
Thanks for filing an issue for this! I was also thinking about it.

(3) sounds like the easiest and most straightforward solution.

I wonder if just extending the `exclude` option here would solve this:

https://github.com/google/web-stories-wp/blob/ca350d4de21ed81f4a5d4c4f88fc3b4f1ee31dec/webpack.config.cjs#L80

Example:

```
exclude: [
  /node_modules/,
  /testUtils/,
],

**Comment by mohdsayed** [comment]
Excluding ` /testUtils/` like that actually causes a build error at the end.


![image](https://user-images.githubusercontent.com/6297436/138744293-57bd2c34-686e-4592-82a2-0c7d065416ce.png)

**Comment by swissspidy** [comment]
The actual build error:

```
    ERROR in ./packages/story-editor/src/testUtils/renderWithTheme.js 34:9
    Module parse failed: Unexpected token (34:9)
    You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
    | // eslint-disable-next-line react/prop-types
    | const WithThemeProvider = ({ children }) => {
    >   return <ThemeProvider theme={theme}>{children}</ThemeProvider>;
    | };
    | 
     @ ./packages/story-editor/src/testUtils/index.js 17:0-63 17:0-63
     @ ./packages/story-editor/src/index.js
     @ ./packages/wp-story-editor/src/index.js
```

Which in hindsight makes sense since babel-loader would exclude that file.

So I think the better way would be to have a separate [package export](https://webpack.js.org/guides/package-exports/) for test utils.

Unfortunately Jest doesn't support that yet (https://github.com/facebook/jest/issues/9771)

Still, we need to stop `export * from './testUtils';` in `story-editor/src/index.js`

Since we can't use package exports yet, in `wp-story-editor` we can import the test utils like this instead:

```js
import { renderWithTheme } from '@web-stories-wp/story-editor/src/testUtils';
```

That works for me locally.
