### ISSUE TITLE
Page Templates: Show Images when in use

### ISSUE THREAD

**Issue by BrittanyIRL** [google/web-stories-wp#9536]
There was this discussion: https://github.com/google/web-stories-wp/pull/9289#discussion_r729251022 which lead to showing page templates with images in the panel but then when they are in use they will be pulled into the story with the graph paper 'placeholder'. Pretty much everyone was confused by this in bugbash. Collectively between bug bash participates, Will, and Amy we've decided that when a user selects a page template to use in their story it should be pulled into the story WITH those images. Officially gutting the graph paper placeholder usage. 

Acceptance criteria: 
- page templates when used will show in story with images as they show in the panel.

**Comment by BrittanyIRL** [comment]
@csossi this is needed for release, pretty please if you have time to prioritize it!

**Comment by csossi** [comment]
Verified in QA
