### ISSUE TITLE
Layer Panel: Increase size of layers

### ISSUE THREAD

**Issue by samwhale** [google/web-stories-wp#9540]
## Feature Description

The rows in the layer panel are a little too small and the preview is hard to see. The layer size will increase, along with the preview so that it is easier for users to see.

**TODO**
- [ ] Designs

## Alternatives Considered

n/a

## Additional Context

Chatted with @agingoldseco about the layers in the layer panel.

**Comment by swissspidy** [comment]
Really? 😅 

We just decreased the size last week in #9366 as per updated designs in #9254 🙃

**Comment by samwhale** [comment]
I'll bring this up with @agingoldseco for second thoughts 👍

**Comment by samwhale** [comment]
Chatted with Amy - this is not going to be done
