### ISSUE TITLE
Right Click Menu Animation 

### ISSUE THREAD

**Issue by BrittanyIRL** [google/web-stories-wp#9563]
## Feature Description

Brought up by @agingoldseco in bug bash:
> I think I’d like to see the right click menu fade in a little faster—it feels like it’s delayed when that may just be an animation choice? Or it is actually slightly slow and the animation makes it feel a bit slower 

Eng to work with design to figure out improvements. 

### Update from design sync 11/9/2021

Going to remove the animation completely, set the default direction of the menu to open _down_ and if there's not room for that, have it open _up_, justified to the bottom right (LTR) - left (RTL) -  corner.

**Comment by csossi** [comment]
Verified in QA
