### ISSUE TITLE
Media: Wrong video file chosen when using VideoPress / WordPress.com

### ISSUE THREAD

**Issue by LuckynaSan** [google/web-stories-wp#9564]
## Bug Description

.MOV videos uploaded in the media library then converted to .MP4 are failing to play in the editor and when previewing the Story. Example story: https://cmsdevrel.wpcomstaging.com/web-stories/test-video-1 (issue on page 2&3)

## Expected Behaviour

Videos in .MOV file format that are uploaded into the media library and gets converted to .MP4 should play in the editor and when previewing.

## Steps to Reproduce
1. On a WordPress.com-hosted website (requires Business Plan or above to install plugins), install the Web Stories plugin > upload a .MOV video via the Media Library or Upload button in the Editor
3. Insert the media into the Story. Note that it does not auto-play and clicking play on the image does not play the video.
4. Preview the story and note the video failed to play

## Additional Context

Original report: https://wordpress.org/support/topic/videos-im-uploading-to-web-stories-wont-play

- Plugin Version: 1.13.0
- WordPress Version: 5.8.1
- Operating System: macOS
- Browser: Chrome

**Comment by swissspidy** [comment]
@LuckynaSan I've added a fix to that testing site. Does it work correctly now? Then I'll add this to our next release
